### ISSUE TITLE
Please use github.com/thermeon/go-logs for logging

### ISSUE THREAD

**Issue by 314159** [udayangaac/boilerplate-golang#13]
Please don't re-invent logging.

**Comment by udayangaac** [comment]
Yes we can use existing logger for this. But I created a log package here because I wanted to put a traceable id for each log messages. Current implementation (github.com/thermeon/go-logs) don't have that feature.
<img width="1361" alt="Screenshot 2022-01-26 at 06 43 21" src="https://user-images.githubusercontent.com/49243124/151086590-b21edccb-795a-4b08-92a0-53986210de18.png">
